#機械学習の勉強

In [ ]:
import pandas as pd

In [ ]:
cats_data={
'ハッピーキャットの労働時間':[160,160],
'チピチャパ猫の労働時間':[161,175]
}

df=pd.DataFrame(cats_data)
df   #dfの表示

In [ ]:
#セルの途中の場合、print関数を利用しないと表示できない
print(type(df))
df.shape

In [ ]:
df.index=['４月','５月']
df   #表示

In [ ]:
monsters_data={
    'businyan':['ブシニャン',150,150,'風',15,10],
    'kyuubi':['キュウビ',150,150,'火',25,10]
}

df=pd.DataFrame(monsters_data)
df.index=['name','hp','max_hp','element','ap','dp']
df

In [ ]:
monsters_data={
    'businyan':['ブシニャン',150,150,'風',15,10],
    'kyuubi':['キュウビ',150,150,'火',25,10]
}

df=pd.DataFrame(monsters_data)
df.index=['name','hp','max_hp','element','ap','dp']
df.columns=['味方１','味方２']
df

In [ ]:
print(df.index)
print(df.columns)
df.shape

In [ ]:
time_data=[
    [160,161],
    [160,175]
]

df2=pd.DataFrame(time_data,index=['４月','５月'],columns=['ハピの労働','チャパの労働'])

df2

In [ ]:
time_data=[
    [160,161],
    [160,175]
]

df2=pd.DataFrame(time_data)

df2

In [ ]:
df.shape

In [ ]:

import pandas as pd

df4=pd.read_csv('KvsT.csv')
df4.head(3)
df4.shape

In [2]:
import pandas as pd

df4 = pd.read_csv(r'C:\Users\natsu\Desktop\機械学習\datafiles\KvsT.csv')

print(df4.head(3))
print(df4.shape)

    身長  体重  年代    派閥
0  170  60  10   きのこ
1  172  65  20   きのこ
2  170  60  30  たけのこ
(19, 4)

In [5]:
df4['身長']

0     170
1     172
2     170
3     170
4     177
5     168
6     169
7     170
8     180
9     170
10    165
11    170
12    175
13    170
14    170
15    155
16    160
17    170
18    175
Name: 身長, dtype: int64

In [7]:
col=['身長','体重']
df4[col]

     身長  体重
0   170  60
1   172  65
2   170  60
3   170  65
4   177  65
5   168  55
6   169  65
7   170  62
8   180  70
9   170  68
10  165  65
11  170  72
12  175  77
13  170  65
14  170  65
15  155  56
16  160  56
17  170  65
18  175  60

In [3]:
df4.tail(3)

     身長  体重  年代    派閥
16  160  56  20  たけのこ
17  170  65  40   きのこ
18  175  60  20  たけのこ

In [5]:
type(df4['派閥'])

pandas.core.series.Series